# Generated by Django 5.2.8 on 2025-11-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_useraccount_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='customeradd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('pan', models.CharField(max_length=20, unique=True)),
                ('aadhaar', models.IntegerField(max_length=20, unique=True)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'customer_add',
            },
        ),
    ]
