# Generated by Django 5.2.8 on 2025-11-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customeradd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeradd',
            name='id',
        ),
        migrations.AddField(
            model_name='customeradd',
            name='accnumber',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
