# Generated by Django 5.2.8 on 2025-11-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_customeradd_id_customeradd_accnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeradd',
            name='accnumber',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
