# Generated by Django 5.2.8 on 2025-11-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_customeradd_accnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeradd',
            name='aadhaar',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customeradd',
            name='accnumber',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customeradd',
            name='pan',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='customeradd',
            name='phone',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
